### ISSUE TITLE
Cannot use multiple GPU cards, single 4090 cannot run

### ISSUE THREAD

**Issue by singeleaf** [meta-llama/llama-agentic-system#32]
The startup command is as follows
`
llama inference start
`

The error of using multiple GPU cards is as follows
`
AssertionError: Loading a checkpoint for MP=1 but world size is 2
`

Single card 4090 error is as follows
`
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB
`

/root/.llama/configs/inference.yaml
````
inference_config:
  impl_config:
    impl_type: inline
    checkpoint_config:
      checkpoint:
        checkpoint_type: pytorch
        checkpoint_dir: /mnt/hfd/Meta-Llama-3.1-8B-Instruct/original/
        tokenizer_path: /mnt/hfd/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
        model_parallel_size: 1
        quantization_format: bf16
    quantization: null
    torch_seed: null
    max_seq_len: 1024
    max_batch_size: 1
````

**Comment by MontaEllis** [comment]
I found that the code requires about 56GB of GPU memory, so I used an A100.

**Comment by UmutAlihan** [comment]
I am expecting for single-node multi-gpu support. Since codebase seems to potentially available for implementation of accelerate package, which provides auto gpu device mapping and reaaallly helps for homelab selfhosted enthusiasts who are utilizing their own small, cheap hardware (such as 2x 3060 on a single server).

Cheers

**Comment by chrismrutherford** [comment]
Somebody?  Surely this library supports single node multiple gpu.  Could it be a configuration issue such as tensor parallel?  Its useless without single node multiple gpu.  Next people will be saying it doesn't support quantization.  Please tell me im wrong.

**Comment by ashwinb** [comment]
It does support multi-gpu as long as the weights are in the appropriate format. For example, the 70B weights are for 8 GPUs. 

Of course, this does not help you because what you want is 8B weights for 2 GPUs -- i.e., you want dynamic splitting of the weights into the GPUs. We are working on getting this working very soon (hint: ollama)

**Comment by jeffxtang** [comment]
@ashwinb Is it correct that `llama inference start` with 8B requires 56GB of a single GPU? Would using FB8 quantization help? 

I got `CUDA out of memory` on a 4xA10G GPUs (each with 24GB), with`quantization_format` set to be either fp8 or bf16. But I can run `torchrun` with the 8B model on the same machine (nvidia-smi shows ~16GB used). Why `llama inference start` would require more than 24GB?

**Comment by ashwinb** [comment]
@jeffxtang that is not expected. We certainly haven't yet tested with other GPUs at all yet, but a 8GB model at bf16 should roughly take ~20GB altogether after doing inference. Can you share your exact configuration? And the memory usage shown by nvidia-smi / nvtop before starting the inference server? Did you load up the safety models also? 

Also note that we have significantly changed how we set up inference now in the toolchain -- we have introduced `Llama Stack Distributions` -- see https://github.com/meta-llama/llama-toolchain?tab=readme-ov-file#llama-stack-distribution as well as https://github.com/meta-llama/llama-agentic-system/tree/main?tab=readme-ov-file#getting-started-with-the-llama-stack. This is not going to drastically affect the performance and your issue by itself (for now), but it changes what commands you need to use, etc. hence pointing it out.

**Comment by jeffxtang** [comment]
@ashwinb the [llama inference start.log](https://github.com/user-attachments/files/16554154/llama.inference.start.log) has the configuration info and the OOM message. 

This is the nvidia-smi info before running "llama inference start":
<img width="919" alt="image" src="https://github.com/user-attachments/assets/440a01b6-3fa7-4406-9114-5e4860db4553">

This is what it shows right before the OOM error (no memory changes on the other 3 GPUs):
<img width="946" alt="image" src="https://github.com/user-attachments/assets/a124eb32-0679-47c7-ae47-9e78910239c8">

Yes I saw about 16+GB used when running torchrun with the 8B model successfully making the inference.

No I didn't have the safety model loaded or downloaded. 

About the new Llama Stack Distribution, is "llama inference start" now replaced with "llama distribution start"?

**Comment by ashwinb** [comment]
Yes, first you need to "install" a distribution using 

`llama distribution install --spec local --name my_llama_distro` 

^ This sets up all the conda environment etc. 

Of course you should re-download the model using `llama download` since now it puts the model in a specific place (if you know where it is putting in and how, you can even move the existing checkpoints yourself.) 

Then you can run `llama distribution start --name my_llama_distro --port 5000`

**Comment by jeffxtang** [comment]
I followed the repo README and installed a local distribution and `llama distribution start --name inline-llama-8b --port 5000` still generates the error CUDA out of memory. 

It's unclear from README that after the conda env `inline-llama-8b` gets created automatically during install, whether one should activate it before running `llama distribution start`, which I tried from both my original conda env and the auto-created one, with the same error.

My `~/.llama/distributions/inline-llama-8b/config.yaml` is below:
```
name: inline-llama-8b
spec: local
conda_env: inline-llama-8b
providers:
  inference:
    provider_id: meta-reference
    model: Meta-Llama3.1-8B-Instruct
    quantization: null
    torch_seed: null
    max_seq_len: 2048
    max_batch_size: 1
  safety:
    provider_id: meta-reference
    llama_guard_shield: null
    prompt_guard_shield: null
  agentic_system:
    provider_id: meta-reference
```

@ashwinb
